{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azp-agent.secretName" . }}
  labels:
    {{- include "azp-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "token or existingSecret is required" .Values.token | quote }}
{{- end }}
